# 添加配置第三方数据库连接池 Druid
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 20
            min-idle: 10
            max-active: 100
        url: jdbc:mysql://localhost:3306/blog_system?serverTimezone=Asia/Shanghai&userSSL=false
        username: root
        password: root