spring:
    data:
        redis:
            host: 192.168.1.190
            port: 6379
            password: 123456
            jedis:
                pool:
                    max-active: 8
                    max-wait: -1
                    max-idle: 8
